# -*- coding: utf-8 -*-
"""Clase 2 – Espectrogramas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dIcQPuM1nVWeqIV2EpQpPx8lR4Jq-vd9
"""

# Se importan las dependencias y librerías necesarias
import tensorflow as tf
import pathlib as pl
from tensorflow import keras
import pandas as pd
import numpy as np
from utils import *
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import matplotlib as mpl
from plotly.graph_objects import Figure, Scatter
import plotly.graph_objects as go
import numpy as np
from IPython import display
from keras.models import Sequential
from keras.layers import Dense, Input,Conv2D, MaxPooling2D, Flatten
from keras.utils import plot_model
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

import warnings
warnings.filterwarnings('always')

def plot_training_loss(loss_data, imagen_path, title='Training Loss Evolution', yaxis='Loss', xaxis='Epochs', label_line='Last Training Loss'):
    """
    Plots the training loss evolution over epochs and adds a dotted horizontal line at the last loss value.

    Parameters:
        loss_data (list): A list containing the loss values for each training epoch.
        imagen_path (Path): Directory path where the graphs will be saved.
        title (str, optional): The title of the plot. Defaults to 'Training Loss Evolution'.

    Returns:
        None: Displays the plot.
    """
    epochs = range(1, len(loss_data) + 1)

    # Creating a DataFrame for use with Plotly Express
    data = pd.DataFrame({
        'Epochs': list(epochs),
        yaxis: loss_data
    })

    # Creating the line plot
    fig = px.line(data, x='Epochs', y=yaxis, title=title)

    # Adding a horizontal dotted line at the last training loss value
    last_loss = loss_data[-1]  # Last training loss value
    fig.add_hline(y=last_loss, line_dash="dot",
                annotation_text=f"{label_line}: {last_loss:.4f}",
                annotation_position="top right")

    # Updating the layout to add more details
    fig.update_layout(
        xaxis_title=xaxis,
        yaxis_title=yaxis,
        legend_title="Legend",
        title={'text': title, 'y':0.9, 'x':0.5, 'xanchor': 'center', 'yanchor': 'top'}
    )

    # Saving the plot as an HTML file
    fig.write_html(imagen_path.joinpath(f'{title}.html'), auto_open=False)
    fig.show()

# Se crea una función que cargo los archivos de audio y genera un vector en
# numpy con las muestras del mismo
def load_wav_16k_mono(filename):
    # Load encoded wav file
    file_contents = tf.io.read_file(filename)
    # Decode wav (tensors by channels)
    wav, sample_rate = tf.audio.decode_wav(file_contents, desired_channels=1)
    # Removes trailing axis
    wav = tf.squeeze(wav, axis=-1)
   # sample_rate = tf.cast(sample_rate, dtype=tf.int64)
    # Goes from 44100Hz to 16000hz - amplitude of the audio signal
   # wav = tfio.audio.resample(wav, rate_in=sample_rate, rate_out=16000)
    return wav

current_path        = pl.Path.cwd().parent #Current working directory
output_folders      = create_output_directories(current_path)
data_folders_path   = create_data_directories(output_folders[0])
imagen_path         = create_img_directories(current_path)
audio_path          = data_folders_path[0].joinpath('Clase 2')
audio_list          = list(audio_path.glob('*.wav'))

audio_list

audio_list[0]

"""# Cuantos archivos hay?"""

len(audio_list)

# Ejemplo de carga de un archivo
RutaFile=str(audio_list[0])
wave = load_wav_16k_mono(RutaFile)
print(wave.shape)

create_line_chart(
    wave,
    title='Clase 2 - Audio 1',
    image_path=imagen_path,
    xaxis='Samples',
    yaxis='Amplitude'
)

# Se define una función que con las muestras del archivo de audio, genera el
# espectograma
def preprocess(wave):
    """
    Generates a spectrogram from the first 16000 samples of the audio wave.

    Args:
    wave (numpy.ndarray): Audio wave array.

    Returns:
    tensorflow.Tensor: Spectrogram represented as a 2D tensor.
    """
    wav = wave[:16000]
    spectrogram = tf.signal.stft(wav, frame_length=255, frame_step=128)
    spectrogram = tf.abs(spectrogram)
    return spectrogram

# Ejemplo de la creación de un espectrograma
espectrograma= preprocess(wave)
print('Waveform shape:', wave.shape)
print('Spectrogram shape:', espectrograma.shape)
print('Audio playback')
display.display(display.Audio(wave, rate=16000))

"""![image.png](attachment:image.png)"""

def plot_spectrogram(spectrogram, title='Spectrogram'):
    """
    Plot a spectrogram using Plotly.

    Args:
    spectrogram (numpy.ndarray): Array containing the spectrogram data.
    title (str): Title of the plot.

    Returns:
    plotly.graph_objects.Figure: A Plotly figure object.
    """
    # Avoid taking the logarithm of zero by adding a small number
    epsilon = 1e-10
    # log_spec = np.log(spectrogram.T + epsilon)
    log_spec = np.log(spectrogram.T)
    height = log_spec.shape[0]
    width = log_spec.shape[1]

    # Creating the x and y scales
    x = np.linspace(0, spectrogram.shape[1], num=width)
    y = np.linspace(0, spectrogram.shape[0], num=height)

    # Create a plotly figure
    fig = go.Figure(data=go.Heatmap(
        z=log_spec,
        x=x,
        y=y,
        colorscale='Viridis'
    ))

    fig.update_layout(
        title=title,
        xaxis_title='Time',
        yaxis_title='Frequency',
        xaxis=dict(showgrid=False),
        yaxis=dict(showgrid=False),
    )

    return fig

# Plot waveform
fig_wave = go.Figure(data=go.Scatter(y=wave))
fig_wave.update_layout(title='Waveform', xaxis_title='Time', yaxis_title='Amplitude')

# Plot spectrogram
fig_spectrogram = plot_spectrogram(espectrograma.numpy())

# Display plots
fig_wave.write_html(imagen_path.joinpath('Clase 2 - Waveform.html'), auto_open=False)
fig_spectrogram.write_html(imagen_path.joinpath('Clase 2 - Spectrogram.html'), auto_open=False)
fig_wave.show()
fig_spectrogram.show()

def plot_3d_spectrogram(spectrogram):
    """
    Plots a 3D spectrogram using Plotly.

    Args:
    spectrogram (tensorflow.Tensor): A 2D tensor containing spectrogram data.

    Returns:
    None: Displays a 3D plot.
    """
    # Convert the spectrogram to a numpy array for plotting
    spectrogram_np = spectrogram.numpy()

    # Get the magnitude of the spectrogram
    magnitude = np.abs(spectrogram_np)

    # Create x, y, z data for 3D plotting
    x = np.arange(magnitude.shape[1])
    y = np.arange(magnitude.shape[0])
    X, Y = np.meshgrid(x, y)
    Z = magnitude

    # Create a 3D surface plot
    fig = go.Figure(data=[go.Surface(z=Z, x=X, y=Y, colorscale='Viridis')])
    fig.update_layout(title='3D Spectrogram', autosize=True,
                    margin=dict(l=65, r=50, b=65, t=90))
    fig.write_html(imagen_path.joinpath('Clase 2 - 3D Spectrogram.html'), auto_open=False)
    fig.show()

# Plot the 3D spectrogram
plot_3d_spectrogram(espectrograma)

# Se cargan los diferentes archivos  de audio que se van a usar en el proceso
# de entrenamiento y se genera el espectrograma de cada uno de ellos

RutaFile= str(audio_list[7])
wave1a = load_wav_16k_mono(RutaFile)
espectrograma1a= preprocess(wave1a)

RutaFile= str(audio_list[8])
wave1b = load_wav_16k_mono(RutaFile)
espectrograma1b= preprocess(wave1b)

RutaFile= str(audio_list[9])
wave1c = load_wav_16k_mono(RutaFile)
espectrograma1c= preprocess(wave1c)

RutaFile= str(audio_list[10])
wave1d = load_wav_16k_mono(RutaFile)
espectrograma1d= preprocess(wave1d)

RutaFile= str(audio_list[14])
wave2a = load_wav_16k_mono(RutaFile)
espectrograma2a= preprocess(wave2a)

RutaFile= str(audio_list[15])
wave2b = load_wav_16k_mono(RutaFile)
espectrograma2b= preprocess(wave2b)

RutaFile= str(audio_list[16])
wave2c = load_wav_16k_mono(RutaFile)
espectrograma2c= preprocess(wave2c)

RutaFile= str(audio_list[17])
wave2d = load_wav_16k_mono(RutaFile)
espectrograma2d= preprocess(wave2d)

RutaFile= str(audio_list[21])
wave3a = load_wav_16k_mono(RutaFile)
espectrograma3a= preprocess(wave3a)

RutaFile= str(audio_list[22])
wave3b = load_wav_16k_mono(RutaFile)
espectrograma3b= preprocess(wave3b)

RutaFile= str(audio_list[23])
wave3c = load_wav_16k_mono(RutaFile)
espectrograma3c= preprocess(wave3c)

RutaFile= str(audio_list[24])
wave3d = load_wav_16k_mono(RutaFile)
espectrograma3d= preprocess(wave3d)

"""# Para el training consideramos 4 archivos de audio por clase"""

print(audio_list[7])
print(audio_list[8])
print(audio_list[9])
print(audio_list[10])
print(audio_list[14])
print(audio_list[15])
print(audio_list[16])
print(audio_list[17])
print(audio_list[21])
print(audio_list[22])
print(audio_list[23])
print(audio_list[24])

# Se almacena todos los espectogramas en una varible
Datos=np.zeros((12,124,129))
Datos[0,:,:]=espectrograma1a
Datos[1,:,:]=espectrograma1b
Datos[2,:,:]=espectrograma1c
Datos[3,:,:]=espectrograma1d
Datos[4,:,:]=espectrograma2a
Datos[5,:,:]=espectrograma2b
Datos[6,:,:]=espectrograma2c
Datos[7,:,:]=espectrograma2d
Datos[8,:,:]=espectrograma3a
Datos[9,:,:]=espectrograma3b
Datos[10,:,:]=espectrograma3c
Datos[11,:,:]=espectrograma3d

# Se expande la variable que contiene los espectrogramas para que puede ser
# procesada por el modelo neuronal
print(Datos.shape)
Xtrain=tf.expand_dims(Datos, axis=3)
print(Xtrain.shape)

# Se definen las etiquetas para la salida del modelo
YtrainIni=np.zeros((12,1))
for i in range(4):
    YtrainIni[i]=0

for i in range(4,8):
    YtrainIni[i]=1

for i in range(8,12):
    YtrainIni[i]=2

print(YtrainIni)

# Se convierten las etiquetas a codificación "one hot" que es la
# usará el modelo
Ytrain= keras.utils.to_categorical(YtrainIni)
print(Ytrain)

# Se crea el modelo secuencial en Keras con capas convolucionales 2D
# y una capa clasificador densa tipo softmax
modelo = Sequential()
modelo.add(Input(shape=(124,129,1)))
modelo.add(Conv2D(8, 3, activation="relu",padding="same"))
modelo.add(Conv2D(16, 3, activation="relu",padding="same"))
modelo.add(Conv2D(32, 3, activation="relu",padding="same"))
modelo.add(Conv2D(64, 3, activation="relu",padding="same"))
modelo.add(MaxPooling2D(pool_size=2,strides=2, padding='same'))
modelo.add(Flatten())
modelo.add(Dense(3, activation = 'softmax'))

# Se muestra el resumen de la arquitectura del modelo
modelo.summary()

plot_model(modelo, show_shapes=True, show_layer_names=True, to_file=imagen_path.joinpath('Clase 2 - Model.png'),show_layer_activations=True)

# Se compila el modelo y entrena el modelo
modelo.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
history_model = modelo.fit(Xtrain,Ytrain, epochs=30,batch_size=None)

# Se gráfica la evolución de la pérdida durante el entrenamiento
loss_training       = history_model.history['loss']
accuracy_training   = history_model.history['accuracy']


plot_training_loss(loss_training, imagen_path, title="Clase 2 - Training Loss Graph",yaxis='Loss', xaxis='Epochs', label_line='Last Training Loss')
plot_training_loss(accuracy_training, imagen_path, title="Clase 2 - Training Accuracy Graph",yaxis='Accuracy', xaxis='Epochs', label_line='Last Training Accuracy')

# Se cargan los diferentes archivos  de audio que se van a usar en el proceso
# de testeo y se genera el espectrograma de cada uno de ellos

RutaFile=str(audio_list[12])
wave1at = load_wav_16k_mono(RutaFile)
espectrograma1at= preprocess(wave1at)

RutaFile=str(audio_list[13])
wave1bt = load_wav_16k_mono(RutaFile)
espectrograma1bt= preprocess(wave1bt)

RutaFile=str(audio_list[19])
wave2at = load_wav_16k_mono(RutaFile)
espectrograma2at= preprocess(wave2at)

RutaFile=str(audio_list[20])
wave2bt = load_wav_16k_mono(RutaFile)
espectrograma2bt= preprocess(wave2bt)

RutaFile=str(audio_list[26])
wave3at = load_wav_16k_mono(RutaFile)
espectrograma3at= preprocess(wave3at)

RutaFile=str(audio_list[27])
wave3bt = load_wav_16k_mono(RutaFile)
espectrograma3bt= preprocess(wave3bt)

Datost=np.zeros((6,124,129))
Datost[0,:,:]=espectrograma1at
Datost[1,:,:]=espectrograma1bt
Datost[2,:,:]=espectrograma2at
Datost[3,:,:]=espectrograma2bt
Datost[4,:,:]=espectrograma3at
Datost[5,:,:]=espectrograma3bt
print(Datost.shape)
XVal=tf.expand_dims(Datost, axis=3)
print(XVal.shape)

print(audio_list[12])
print(audio_list[13])
print(audio_list[19])
print(audio_list[20])
print(audio_list[26])
print(audio_list[27])

# Se definen las etiquetas para la salida del modelo
YValIni=np.zeros((6,1))
for i in range(2):
    YValIni[i]=0

for i in range(2,4):
    YValIni[i]=1

for i in range(4,6):
    YValIni[i]=2

print(YValIni)
# Se convierten las etiquetas a codificación "one hot" que es la
# usará el modelo
YVal= keras.utils.to_categorical(YValIni)

print(YVal)

# Se evalua el modelo con los datos de testeo
modelo.evaluate(XVal, YVal)

ypredic=modelo.predict(XVal)

y_test_class = np.argmax(YVal,axis=1)
y_pred_class = np.argmax(ypredic,axis=1)

#Accuracy of the predicted values
print(classification_report(y_test_class, y_pred_class)) # Precision , Recall, F1-Score & Support
cm = confusion_matrix(y_test_class, y_pred_class)
print(cm)
# visualize the confusion matrix in a heat map
df_cm = pd.DataFrame(cm)
heatmap = sns.heatmap(df_cm, annot=True, fmt="d")